sudo: required
language: ruby
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
- docker-compose ps
script:
- "./test.sh"
after_success:
- "./deploy.sh"
env:
  global:
  - secure: D3ddKl3sJi5JGpLMqL6CFK+YeSyblewTAy+DdLCCRNemQbSViO4SuUpiFEfV/1PRdK3L8a67+JrTZ6939fPrTfUzdfGZ8y5DkxRk/K6Pj5wexfYdiifQqBXe34QJddl/Ns0GO6svT2bWdLfxjf6Oh1dKBGbPxyWnwv1DRhrsyt9Q9yhwzS0XV+Wy+V564da6ham26aBISrTUIci4B0bb/9LuJp1DWKQoKZfAUNRVtVT5/PgapwjHK/bPuIbc+BG5FsG12xHV1N1jaeFz8xYDQwAVxFCzbTpjfn+ja848XxLMzgFf2SNIxM9yxgVYjI0iYAlxEP7R94FcUWikSsjx09kEUumkxFkeEj5vdwhp7PiWYtB8cJWnf8MNgTWWkuS1hqm+c+j2l1yIH+eGIxlFp0zmFxrksvEBb6PkWQ3kOA/eVOwMwsNY76LdJYe5kTtGaZNJVHCRmVXw6AhPf13HY8fzmM5Ua1DsF8gK788HG9xSPhIo1+87J/lWEis8paGJTccH9boqa8eY+4ytNadqC+tQ1daMyDjaIEvYRf0fuypMyyqTznsfuCO0b8oKCCnD8Ocra+Heed+pzsG8onY5j/F+PjVdumJuBjUdXtxka6kGJdwEL6WoxCy/UlcvjcMIZmSI5N7DgkAPdSpE9HpRoZYShQtbDRGy473GTvKZVX4=
  - secure: SVPmUB79oGJ0S1nqV0TjVvnkmpXc6xCg7n+M+is/YFsJobeBSqYo1udXoYfYRA41p9IYYuMcdxK5uTeKOIHLX3r5u8ZQ6c/QM+IU31lebCTIUoHvj4J9UyINBD+WNNy1C8o+jGEtEid0TOq0pslSIgeQmfGX9ZPqWdq3ZahcMY9k5w9n0JgRTZxAKnVGINowBOX30PUHXaMWDBwmyrQejamuQ3NDwN3k3Gm40CEZS51Qn7T9zWrV0xi+oL/Qtac74Z+n6qLLZJ9tu6Ef73N3ymThJgE9nuewUsJ9xwiVoinkY56WMiubphrDe8uHXujA9hlG39I861mnMGsRjJ0O5Zpwk58PqXtbYUP7T+kYiXjfCO4u3FaWjfUfrT/9neSmLF8c+ZMrMdgqV8DyKR3/tVl7B0a0qTBkcKMB8Z0aN2rk/ifsXbF30YPchGMZEZascuF+OmxI3GVOTCVXAp2kPpJbmR9MdZDmibPEv101W9iD0OQJyCV0h8ggJJRH4E/N87/9zJgXT3sbcELogfGd53ZVXMPgNZrTGzYhT0x/sbR+PdytCPOsjtJgTVlW5j1vVPdTHbtY4tqJoP6rGZ2jjtqd71CHAkUzZUvr4i+haiHkO/cN8Oho2VC+8bCZ31kP2Kvp3+t32z0BZZxBjUGTteyTWFQk0Tp03Bs1s3+DzWw=
