sudo: required
language: ruby
services:
- docker
before_install:
- echo DOCKER_HUB_USERNAME
- docker-compose build
- docker-compose up -d
- docker-compose ps
script:
- "./test.sh"
after_success:
- "./deploy.sh"
env:
  global:
  - secure: D3ddKl3sJi5JGpLMqL6CFK+YeSyblewTAy+DdLCCRNemQbSViO4SuUpiFEfV/1PRdK3L8a67+JrTZ6939fPrTfUzdfGZ8y5DkxRk/K6Pj5wexfYdiifQqBXe34QJddl/Ns0GO6svT2bWdLfxjf6Oh1dKBGbPxyWnwv1DRhrsyt9Q9yhwzS0XV+Wy+V564da6ham26aBISrTUIci4B0bb/9LuJp1DWKQoKZfAUNRVtVT5/PgapwjHK/bPuIbc+BG5FsG12xHV1N1jaeFz8xYDQwAVxFCzbTpjfn+ja848XxLMzgFf2SNIxM9yxgVYjI0iYAlxEP7R94FcUWikSsjx09kEUumkxFkeEj5vdwhp7PiWYtB8cJWnf8MNgTWWkuS1hqm+c+j2l1yIH+eGIxlFp0zmFxrksvEBb6PkWQ3kOA/eVOwMwsNY76LdJYe5kTtGaZNJVHCRmVXw6AhPf13HY8fzmM5Ua1DsF8gK788HG9xSPhIo1+87J/lWEis8paGJTccH9boqa8eY+4ytNadqC+tQ1daMyDjaIEvYRf0fuypMyyqTznsfuCO0b8oKCCnD8Ocra+Heed+pzsG8onY5j/F+PjVdumJuBjUdXtxka6kGJdwEL6WoxCy/UlcvjcMIZmSI5N7DgkAPdSpE9HpRoZYShQtbDRGy473GTvKZVX4=
  - secure: WBeibiXt8hzaHBKMJyyFUu5LkBnHjMudti4HHGSyVWUNMCiC8biTvqLF7o6TRhZvts40JDIW1stX+BAMtePm76XBEBYvE2e0IJ7bJkpE2dOn6wFyPZgYNVkx4V6jRkhlrRr9vAC+kCN3eZKrTiM2PLx/DGK2kFH4SJb7FRc6tDJexVnuug0yo7KmzOuBnWhljJ/SEKutLDV2bSTtTwotT2opt6GHei8lB3uwGPRJTKZ+InM7W+dFusRfu2V/T3buY5cw+6ra3sG6bjy1sKz3as8o4SOgdPyngYr7uT6HjQDXStmcL3Lok65Wz4xzi52/mWtfG4QNLNqH7tWilnc9yRIlDThRFPspmwFciG+EtCGLIPw8V90UIwvaNx1h/+R3a6nhqn0vBX47xKPYrc06GpuIG6MSsX4cDTkswcwMqD16V4+64JV1IldGGP0G10TOfH7b6jnIh5H1jUbDUq6WPkIbwM5zXRL/gENQB8Q0x3GVwkE8tC0rfVf9d4nooR16dx63hP7jGdBEA+Mw1/b3JhT+elPAEo6E6KfWY0EJsj0xIVcELoSAyOlyDUFTsiwarKPAF0zE0c+Vzy5zbVIh80tmt1PUp/ZP1vkc6+cSchHFYdaz7fD3DJGEqXGG2A6AXQ2AIVFmHEXJAn0YdcI9pmc81tDH0snq183ylo4ySK4=
