sudo: required
language: ruby
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
- docker-compose ps
script:
- "./test.sh"
after_success:
- "./deploy.sh"
notifications:
  slack:
    secure: n1h+PaQQCs6NUG/w1qKn7fpK6nmhdplymiVc4WmPxDtoCmYwKkciBvQs0RBTTafJxk5QFEfDkWjXLw/SH7Xd4f20FSStmLOgHNadfqk6iOL4lx8PWM3EO2pGqJZnHRlcBScdwPIUN2uGRqJX+yOxNkWaBTfzi2nI9psUNJzHI7EG/Xc5UcomvR0hvJfEu2AMZrxuH9wWvBMgTekJk7+hcrWfe7FEvok8uSVPEGKWCeu0V6WcJ9mOuEJK+HVZWb7ngOkDoIhtAlzf0KSc6sjvt+xoToM5T84KqcVpKNHH518pEtFjlGjwMFJDhjGKZ/B3g9aDjtzZ0LRYQ9mpyEmjKSbMxvyT36+t//Xs2+ZXjnihHyMFBnuHz7RmJulNHRonZyPDrQ7JH+fNrUJ/yR4f6BSpvILde/eTh6Z+PCV8sGK0d3YXDiCvC5vVcMj3VlDHwTEQuDH4JvSrewwWOZd542G6Ijpo3D4rGxcJlkqnC7Amd2LhlDTFJmVHy957AFRS45M12yT9xmqwEG8oLc8V0wEdtItAYx1C1zNX1JYAqs66xTN+7NWGq4I6jDiRA4Bjdxh/Cek9zr4U/AhaCPYfXzkodU2XCvrMhX1USVLO4weDYShHTEP8hucbrVIiXZv2Ubp3UIUaEwWWq5BsESDfozibTE2Cjod4wviGQbS9Sgs=
env:
  global:
  - secure: VdLGewQyGQNtjWJeJtoH2cT+92D0oh4p1CyAAEUWzn/l7jz25TEVXN0zHc8+DtSNl2JepYpIuI/7RyHeYfuMlss24h3YCgg7R98DteAICOMmiJnBdxtIO1Dwg4uw+MJbPtz2Um22+WJ3CM+NP6dMcX6CJewAr0cnypL3nj/XgkG/vkq35nYThaFaeVhuQVdkbjftk7AYnFVypSirX+wFvxNw8egGjO2o/LQmHefKxW53/GWSmnSHc55wzP0Au2YZNNbIeL5lb97+CVMXQRtSUWy6kM86EUILrJfHI5llXcEg5ZpvE1APITzcRKIHXHtDI/e91Y9Axsodar7knrU8214PVicKYOdVKZBQwlxLo0eJeLgH+/jMZze4rGYtH94lFCPDpO7KuAOcnD3zwpE7yRm1EYCH8jnbsa1FHRlmjQihtbLJdnsdxXDQfshvV6CJfObfSc46b/eQqGFhET+HSoeq7Wsa+WWbf9k6jReHw5YulZWNQlK3VxPXIlr227+jbLR95s7JpMxkcC1CPsJ7JjSi/wxsTstysLmHSTrQs+Xs+9VnJ/QT2nBaeVSNlBanhwBcKKrMYTGuI5U6TompjS7OOimEoECeS5f/tuS7vw6dCB61EFHJcm8pSB5AicQ3TV7xbF+Eg9WjGwp9VHdTxMAudH1yVTTkDw4JjHzItBk=
  - secure: ajoA/X3Vm1Kc3AWuHPJegSRHUHDL2V/Mw8EcyqwcZBCMNMgdLEcpedAKAMcwa6Aev22yNLXNPnMNW5IKr7hdQvgN8KHAZpkET39HhkskZtra90DDG/7vZEYfwtFBqn4GHqFObIc5cwASRUuYIz4QdY8nt+wmJvJlThtDTaoovSFXQkAvY16xJ7trVnoTNxCgMIDya62EdOdca5eju6+3kUCgURQFlV7Q1K3Sl9KPBSa2W+8I3f/IOdfHFD5ytHD1oc//RpmAMByk/U3mFyODBRi/+bnNPjMxp3s7d+iFR8Rabmy9xBUzWT5rB/GGRKJoQ+GHnF5iIHxglbQkRG/Ex2arW/6A27V6l5p2d9eKuF6l77Uk8aKf3JeL226sXd8FHMoYZfhmI+DhdjtUJDY/3xOPBFS4/jbhp39AW/NDnsicSX0ncQYpeDZNiW6D0EToZvWx5JmQjofYMPfgXVKiuOMG7I4C2bIoTa5bhZx/k5uIge26JkQjj9J+icDXKhbQdomBFHQgufjzJ+lJkR6NGwSA7bzuEN1U7WJAH768oACTPbrLweNDBXgcKjS6D+2wvMV7+/gBu4Z1Qt7+/Ig/sOQFY9PM3xduCGx+FC+5zhweilQSgF4xXtoSIpVPvh88y9MxW8FvUEots9hMp84tQP6wX/genKNtA/2uj91zqdI=
