version: '2'
services:
  mtproxy:
    image: kolahzary/mtproxy:1.0 # MTProxy docker image without hard-coded limitations
    volumes:
       - "./mtproxy/:/data"
    restart: unless-stopped
    environment:
       - WORKERS=1
       - CONNECTIONS=60000
       - SECRET=22409...0000
       - TAG=7ad8d...c7868
  ngrok:
    build: .
    environment:
      - NGROK_TARGET=mtproxy
      - NGROK_PORT=443
      #- NGROK_AUTH=5Sw...YfKn
    depends_on:
      - mtproxy
